title: teleSOHO.com
url: http://telesoho.github.io
description: 'Personal site of Wenhong.Tan, software developer and designer from China'
keywords:
 - Wenhong.Tan
 - telesoho
 - tanbunko
 - wotiger

author:
    name: wotiger
    email: telesoho@gmail.com
    twitter: http://twitter.com/tanbunko
    github: http://github.com/telesoho
    # googleplus: http://plus.google.com/100369739207842495161
    facebook: https://www.facebook.com/bunko.tan
    # linkedin: http://www.linkedin.com/in/michaelmonteleone/
    avatar: https://www.gravatar.com/avatar/d365274aad396f7e9c7c493d36049493?s=70
    # openid:
    #     server: https://www.google.com/accounts/o8/ud
    #     delegate: http://www.google.com/profiles/namelessmike


sections:
 - name: projects
   title: 项目
 - name: journal
   title: 日志
 - name: about
   title: 关于
 
stylesheets:
 - /assets/themes/default/css/screen.css?52480=52480
 - /assets/themes/default/css/print.css
scripts:
 - //ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.1.min.js
 - /assets/themes/default/js/site.js?234343

colors:
    highlights:
        blue: '#009ff7'
        green: '#87d14b'
        red: '#FF007C'
    mono:
        dark: '#000000'
        medium: '#777777'
        light: '#FFFFFF'
    bg: '#EAF1F4'

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true
  # my_tags:
  #   output: true
  #   permalink: /tag/:name/
  #   filepath: /tags
  #   layout: tag_index

# Handling Reading
safe:                 false
include:              [".htaccess"]
exclude:
 - Rakefile
 - README.markdown
 - .git
# exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
plugins_dir:   []

# tag plugin
# tag_page_layout: tag_page
# tag_page_dir: tag
# ignored_tags: []
# tag_permalink_style: pretty

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname
# show_dir_listing: false

# Outputting
permalink: pretty # date
paginate_path: /page:num
timezone: Asia/Shanghai


quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# theme: jekyll-theme-cayman
